### PR TITLE
Nzhao2

### PR DESCRIPTION
**Pull request by NC-Zhao**
The faster parser is here. 
`parser.mix` is for unit test purpose. `parser.old` is the old version.

### CODE REVIEW

**Comment by kamilkrukowski** [comment]
Why do we need ```parser.mix``` and ```parser.old```? What do these files do? How we plan to use them?
Github keeps track of old file versions for free forever in previous commits.

What is the difference between ```f``` and ```driver_path``` in ```_parse_annotated_documents```. You need to update documentation as well, or push new documentation if it's missing.

Why do you change the function contracts? Adding new mandatory arguments and switching old 'arguments' into 'keyword arguments' with default values breaks everyone else's code and forces Kelsey, Amber, and I to rewrite code.

**Comment by kamilkrukowski** [comment]
Also, what unit tests?

You have zero units tests on GitHub for ```parser.mix``` and ```parser.old``` to refer to.

**Comment by kamilkrukowski** [comment]
One last comment: whenever you are available and the necessary changes are made, I'd prefer if we switch to a 'single commit' pull request structure.

This means that unless there is a specific reason, it makes sense to ```squash``` all the commits on this pull request (here are 4 currently) into one rebased commit. For this request, I can do that personally once you indicate the changes are made. This will require you to ```git reset --hard``` after ```git fetch``` to fix your local branch If I am the one doing squashing.

**Comment by NC-Zhao** [comment]
@kamilkrukowski I have squashed all the commits. Those two old .py file has been dropped. 
`parser_test` is replace by .py scripts. The `parser_test` prints out the discrepancies if `parser.py` is replace by `parser-mix.py`. Due to treatment of spaces/newlines/special_characters, the amount of discrepancies is quite large and I have checked them with the source code of the file. Issues were found and fixed. 

I changed the function contract to what it used to be. The major reason I replaced `driver_path` with `f` was that their type is different. Now there won't exceptions raised up if the path is an `os.path` or is generated by `get_driver_path`.

**Comment by kamilkrukowski** [comment]
Looks a lot better! I plan on checking out the branch locally for a quick inspection.
I notice ```parser_test.py``` calls a ```parser.new_parse_annotated_file``` function which strictly doesn't exist in this commit. Maybe we should keep ```parser_test.py``` in a separate test branch but remove it from the pull request?

**Comment by NC-Zhao** [comment]
@kamilkrukowski I created a new branch called `parser-mix` based on nzhao2. `EDGAR\parser.py` has been replace by `parser-mix.py`

**Comment by kamilkrukowski** [comment]
I think this branch should stay permanently, although future development should occur on a different branch.
I am a bit wary of some unexpected behavior or bugs that are hard to see/catch arising in the future.

But this is great work! From a quick testrun it appears that preprocess.py now runs several hundred times faster at the least, and the output does not obviously seem to have reduced quality in any way.

**Comment by kamilkrukowski** [comment]
Okay! We can use ```parser-mix``` as a dev branch to keep track of unexpected behavior for future debugging if necessary. That means we can drop ```parser_test.py``` from this branch and this pull request, then squash commits again. Looks good to approve after that happens.

**Comment by kamilkrukowski** [comment]
Could you recommit after deleting ```parser_test.py``` and squashing?

I'll plan on generating a 'maximal size' dataset locally overnight and I'll plan on reporting dataset generation success/failure on my end sometime over the weekend.

**Review by kamilkrukowski — APPROVED** [review]

**Comment by kamilkrukowski** [comment]
Feel free to apply the merge

**Pull request merged**
